---
version: '3'
services:
  web:
    # image: nginx
    build: nginx/
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    # volumes:
    #  - /home/flask/nginx.conf/genomelocator.conf:/etc/nginx/conf.d/:ro
    #  - /home/flask/certs/:/etc/nginx/certs/
    # command: [nginx, '-g', 'daemon off;']
    networks:
      - my_net
      - ext
    links:
      - genomelocator:genomelocator

  genomelocator:
    build: .
    expose:
      - 5000
    ports:
      - "0.0.0.0:5000:5000"
    networks:
      - my_net

networks:
  my_net:
    internal: true
  ext:
    internal: false

